# Generated by Django 5.2.5 on 2025-08-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='weights',
            new_name='weight',
        ),
    ]
